#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GymDatabase")]
	public partial class ClientsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    #endregion
		
		public ClientsDataContext() : 
				base(global::Thesis.Properties.Settings.Default.GymDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClientsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClientsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClientsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClientsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddClient")]
		public int AddClient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NChar(20)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NChar(20)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubFrom", DbType="Date")] System.Nullable<System.DateTime> subFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubTo", DbType="Date")] System.Nullable<System.DateTime> subTo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubId", DbType="Int")] System.Nullable<int> subId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedAt", DbType="Date")] System.Nullable<System.DateTime> addedAt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumberRenewings", DbType="Int")] System.Nullable<int> numberRenewings, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NChar(30)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NChar(20)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CoachId", DbType="Int")] System.Nullable<int> coachId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bonus", DbType="Bit")] System.Nullable<bool> bonus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, lastName, subFrom, subTo, subId, addedAt, numberRenewings, email, phoneNumber, coachId, bonus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteClient")]
		public int DeleteClient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clients")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.DateTime _SubFrom;
		
		private System.DateTime _SubTo;
		
		private System.Nullable<int> _SubId;
		
		private System.DateTime _AddedAt;
		
		private int _NumberRenewings;
		
		private string _Email;
		
		private string _PhoneNumber;
		
		private System.Nullable<int> _CoachId;
		
		private bool _Bonus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnSubFromChanging(System.DateTime value);
    partial void OnSubFromChanged();
    partial void OnSubToChanging(System.DateTime value);
    partial void OnSubToChanged();
    partial void OnSubIdChanging(System.Nullable<int> value);
    partial void OnSubIdChanged();
    partial void OnAddedAtChanging(System.DateTime value);
    partial void OnAddedAtChanged();
    partial void OnNumberRenewingsChanging(int value);
    partial void OnNumberRenewingsChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnCoachIdChanging(System.Nullable<int> value);
    partial void OnCoachIdChanged();
    partial void OnBonusChanging(bool value);
    partial void OnBonusChanged();
    #endregion
		
		public Client()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubFrom", DbType="Date NOT NULL")]
		public System.DateTime SubFrom
		{
			get
			{
				return this._SubFrom;
			}
			set
			{
				if ((this._SubFrom != value))
				{
					this.OnSubFromChanging(value);
					this.SendPropertyChanging();
					this._SubFrom = value;
					this.SendPropertyChanged("SubFrom");
					this.OnSubFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTo", DbType="Date NOT NULL")]
		public System.DateTime SubTo
		{
			get
			{
				return this._SubTo;
			}
			set
			{
				if ((this._SubTo != value))
				{
					this.OnSubToChanging(value);
					this.SendPropertyChanging();
					this._SubTo = value;
					this.SendPropertyChanged("SubTo");
					this.OnSubToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubId", DbType="Int")]
		public System.Nullable<int> SubId
		{
			get
			{
				return this._SubId;
			}
			set
			{
				if ((this._SubId != value))
				{
					this.OnSubIdChanging(value);
					this.SendPropertyChanging();
					this._SubId = value;
					this.SendPropertyChanged("SubId");
					this.OnSubIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedAt", DbType="Date NOT NULL")]
		public System.DateTime AddedAt
		{
			get
			{
				return this._AddedAt;
			}
			set
			{
				if ((this._AddedAt != value))
				{
					this.OnAddedAtChanging(value);
					this.SendPropertyChanging();
					this._AddedAt = value;
					this.SendPropertyChanged("AddedAt");
					this.OnAddedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberRenewings", DbType="Int NOT NULL")]
		public int NumberRenewings
		{
			get
			{
				return this._NumberRenewings;
			}
			set
			{
				if ((this._NumberRenewings != value))
				{
					this.OnNumberRenewingsChanging(value);
					this.SendPropertyChanging();
					this._NumberRenewings = value;
					this.SendPropertyChanged("NumberRenewings");
					this.OnNumberRenewingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NChar(20)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoachId", DbType="Int")]
		public System.Nullable<int> CoachId
		{
			get
			{
				return this._CoachId;
			}
			set
			{
				if ((this._CoachId != value))
				{
					this.OnCoachIdChanging(value);
					this.SendPropertyChanging();
					this._CoachId = value;
					this.SendPropertyChanged("CoachId");
					this.OnCoachIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bonus", DbType="Bit NOT NULL")]
		public bool Bonus
		{
			get
			{
				return this._Bonus;
			}
			set
			{
				if ((this._Bonus != value))
				{
					this.OnBonusChanging(value);
					this.SendPropertyChanging();
					this._Bonus = value;
					this.SendPropertyChanged("Bonus");
					this.OnBonusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
