<?xml version="1.0" encoding="utf-8"?><Database Name="GymDatabase" Class="SalariesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Model\GymDatabase.mdf;Integrated Security=True" SettingsObjectName="Thesis.Properties.Settings" SettingsPropertyName="GymDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Salaries" Member="Salaries">
    <Type Name="Salary">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Member="Salaryy" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Bonus" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.AddSalary" Method="AddSalary">
    <Parameter Name="WorkerId" Parameter="workerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Salary" Parameter="salary" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Bonus" Parameter="bonus" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSalary" Method="DeleteSalary">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>