namespace Thesis.Model
{
    public enum TableName
    {
        CLIENTS, EXPENSES, INVENTORY, PROCEEDS, PRODUCTS,
        PROVIDERS, SALARIES, SUBSCRIPTIONS, SUPPLIES,
        WORKERS, WORKOUTS, WORKSCHEDULES
    }
}
